# Generated by Django 4.0.3 on 2022-06-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_note_note_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='note_content',
        ),
    ]
