# Generated by Django 4.0.3 on 2022-06-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_content_note_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
    ]
